version: "3"
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - zookeeper
  worker:
    build: ./worker
    networks:
      - app-tier
    depends_on:
      - keycloak
    environment:
      - KAFKAIPADDR=kafka:9092
  api:
    build: ./API-Rest
    ports:
      - '3000:3000'
    networks:
      - app-tier
    depends_on:
      - keycloak
    environment:
      - KEYCLOAKIPADDR=localhost:8082
      - KAFKAIPADDR=kafka:9092
      - KEYCLOAKCLIENT=api-client
      - KEYCLOAKREALM=api-realm
      - KEYCLOACKPUBLICKEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqvPRn8irFTlGw0qAQ5d3GUAGw641h2j3Keowk+eKTvO/sUIE5Mt1UJzFlfWYoNukQxlMPCADqfYBbHXsE7Gru0bYaSN+Oj52TFkZvlIpxbrg/kemEwt6th3PHTyWdz6CYo9slZCmQSGbTojkeLaKbeifpVJa6erSn6ea2l56V6rVg4lkKQrbiWQqM2IRdSwmHd3USniNMtRkd9fIZ6yS38Hjk5zu/3JsKSIQAOV+lwvbiU0fT5ErEpqwpm7l3qzsVoCUE3J7/Arj17DPOeYxiDhNYBkk1+v6BiYzmLi+0UNKMfXf/ctkyD4iJNoEML75VEJr96dsUZX2JYl9iTGZ2QIDAQAB
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: sad-postgresql
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    hostname: keycloak
    networks:
      - app-tier
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
volumes:
  postgresql_data:
    driver: local
