version: "3"
networks:
  app-tier:
    driver: bridge
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-tier
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - app-tier
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKAJS_NO_PARTITIONER_WARNING=1
    depends_on:
      - zookeeper
  worker:
    build: ./worker
    networks:
      - app-tier
    environment:
      - KAFKAIPADDR=kafka:9092
  api:
    build: ./API-Rest
    ports:
      - '3000:3000'
    networks:
      - app-tier
    depends_on:
      - keycloak
    environment:
      - KEYCLOAKIPADDR=keycloak:8080
      - KAFKAIPADDR=kafka:9092
      - KEYCLOAKREALM=kafka-realm
      - KEYCLOACKPUBLICKEY='MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx0O6h6e+jApu9bmENK/llAAQxw7khNuGBL3VwYGa1NVE6VMxGT8o7k0e1RmUqddVw26G+/jsDSt0+4D6bSIPQ/QM+huolmaEE9P/J8aMziu7Hu+tpDp38qoghch3zxGkX+ma827BagC9/Wk2IPqRpBP27VmmeuMOSSEnqrAwc9YdAchwS7pYIT+H9zJUCXTR0C/Jpkm13k050Z7bJlO3VuykJvEtUoEVU29NNpo4bKPntWcwuBJ4dlnKo1TpzWUbVxjm0DXnNSwZGknEX38Z5+3Tm5aSWEWnfxDLlOQhHSScLVML9oFoYKmS1wp6yZ82rkcvIUK/9b3fjk8ziLeD9wIDAQAB'
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: sad-postgresql
    networks:
      - app-tier
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    hostname: keycloak
    networks:
      - app-tier
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
volumes:
  postgresql_data:
    driver: local
